language: python
python:
   - "2.7"
sudo: false
cache:
   directories:
       - "~/.platformio"
install:
   - pip install -U platformio
   - platformio lib --storage-dir lib install DS3231
   - platformio lib --storage-dir lib install "Adafruit Neopixel"
   - platformio lib --storage-dir lib install PCF8574
   - platformio lib --storage-dir lib install I2C_EEPROM
   - platformio lib --storage-dir lib install Radio
   - platformio platforms install atmelavr
script:
   - platformio ci --project-conf=platformio.ini
