language: python
python:
   - "2.7"
sudo: false
cache:
   directories:
       - "~/.platformio"
install:
   - pip install -U platformio
   - platformio lib --storage-dir lib install DS3231
   - platformio lib --storage-dir lib install Adafruit_Neopixel
   - platformio lib --storage-dir lib install Radio
script:
   - platformio run
